### ISSUE TITLE
[NC upstream issue] display and linking of keys not working anymore

### ISSUE THREAD

**Issue by My1** [jaark/twofactor_yubikey#21] opened 2019-01-15 21:54 UTC
Note: quick hack to fix yourself [below](https://github.com/jaark/twofactor_yubikey/issues/21#issuecomment-457955502)

while when I installed the addon for the first time it worked splendidly, it apparently doesnt do so anymore.

I can login fine with no problem and the admin settings API keys, testing etc) work great, but the user settings dont really seem to work:

1) there are no Yubis listed and therefore no deletion possible
2) adding a new Yubi doesnt work either. after pressing enter (or letting the Yubi do so) nothing happens at all.

considering NC 15.0.2 came out fairly recently it might be that it only happened after the update.

of course I did try a full uninstall and reinstall of this plugin.

**Comment by HozerTech** [comment] 2019-01-26 05:01
Just installed today on NC 15.0.2 and have the same issue. Can test but not add

**Comment by My1** [comment] 2019-01-26 10:17
by the way, if you are brave and have no problem playing in the db you can also add the keys manually

the table is `oc_twofactor_yubikey` which contains a numeric index (you dont need to enter anything as this thing has autoincrement), your user_id (your login username but if you need to check the correct spelling check `oc_accounts` or `oc_users`, the uid is what you need. and the last your yubikey public ID, first 12 characters of a yubi-otp as far as I remember, but you can also just go and enter a full yubi-otp, it will throw a warning that it truncated the string (which is precisely what we want) and then it's in.

**Comment by sullenx** [comment] 2019-01-26 17:53
The problem is not in this app. The problem was introduced by Nextcloud. The issue is a javascript error, which crashes jquery: 

> security_password.js?v=cf06679d-9:73 Uncaught TypeError: $(...).strengthify is not a function
    at HTMLDocument.<anonymous> (security_password.js?v=cf06679d-9:73)
    at j (core.js?v=cf06679d-9:2)
    at Object.fireWith [as resolveWith] (core.js?v=cf06679d-9:2)
    at Function.ready (core.js?v=cf06679d-9:2)
    at HTMLDocument.I (core.js?v=cf06679d-9:2)
(anonymous) @ security_password.js?v=cf06679d-9:73
j @ core.js?v=cf06679d-9:2
fireWith @ core.js?v=cf06679d-9:2
ready @ core.js?v=cf06679d-9:2
I @ core.js?v=cf06679d-9:2

You can verify this by opening the javascript console. This file is located in ./settings/js/security_password.js

If you comment the function  $('#pass2').strengthify(....), then everything works as it should. I recommend to close this issue and open a ticket against Nextcloud as we have no workarounds here.

@ChristophWurst  Could you help in resolving this issue within Nextcloud?

**Comment by My1** [comment] 2019-01-26 20:26
so by this logic this also happen in an NC without any plugins, I think I can try that just for the lulz.

**Comment by sullenx** [comment] 2019-01-27 14:44
This javascript exception was already found and fixed in Nextcloud: 
[https://github.com/nextcloud/server/issues/10464](url)

Not know why it's not resolved for us.

**Comment by My1** [comment] 2019-01-27 21:22
well it was a different new issue. someone forgot some files in NC15

https://github.com/nextcloud/server/issues/13520
https://github.com/nextcloud/server/pull/13546

as a quick hack you can copy over the 2 min files from `core/vendor/strengthify` in the [stable branch](https://github.com/nextcloud/server/tree/stable15) into the same folder in their NC (be reminded that you have to delete it again before updating because signatures.

but I at least confirmed it working in my test-nc

edit: leaving open for now that it wont be overlooked (and ppl can fix by themselves) until NC drops 15.0.3 (the planned release for this fix, which will take about a month according to schedule)

**Comment by jaark** [comment] 2019-02-02 11:11
I can confirm this is fixed in NC 15.0.3RC1

**Comment by My1** [comment] 2019-02-02 13:32
great.

**Comment by jaark** [comment] 2019-02-07 18:43
Closing because 15.0.3 is now out.

**Closed as completed by jaark** 2019-02-07 18:43 UTC
